apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations:
    deployment.kubernetes.io/revision: "3" 
  labels:
    app: goweb    
  name: goweb  
  namespace: default

spec:
  selector:
    matchLabels:
      app: goweb
  template:
    metadata:      
      labels:
        app: goweb  
    spec:
      containers:
      - image: goweb:1.1
        imagePullPolicy: IfNotPresent
        name: goweb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-pknqq
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: minikube
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: default-token-pknqq
        secret:
          defaultMode: 420
          secretName: default-token-pknqq  
