apiVersion: v1
kind: Service
metadata:
  labels:
    app: goweb
  namespace: default    
  name: goweb

spec:
  externalTrafficPolicy: Cluster
  ports:  
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: goweb  
  #type: LoadBal  ancer
  type: NodePort